export const ME = "me";

/** Ширина панели бесед в вертикальных макетах (слева/справа), px. */
export const CHAT_LIST_PANEL_WIDTH = 280;

/**
 * Ширина той же панели во всплывающем окне: там в блоке управления есть ещё
 * «развернуть» и «закрыть», и восемь кнопок обычного размера в 280px не помещаются.
 * Расширяем панель, а не уменьшаем кнопки, — размеры иконок везде одинаковые.
 */
export const CHAT_LIST_PANEL_WIDTH_OVERLAY = 380;

export const EMOJI_CATEGORY_EMOJIS: string[][] = [
  [
    "😀",
    "😃",
    "😄",
    "😁",
    "😆",
    "😅",
    "🤣",
    "😂",
    "🙂",
    "😊",
    "😇",
    "🥰",
    "😍",
    "🤩",
    "😘",
    "😗",
    "😚",
    "😙",
    "🥲",
    "😋",
    "😛",
    "😜",
    "🤪",
    "😝",
    "🤑",
    "🤗",
    "🤭",
    "🤫",
    "🤔",
    "🤐",
    "🤨",
    "😐",
    "😑",
    "😶",
    "😏",
    "😒",
    "🙄",
    "😬",
    "😔",
    "😪",
    "🤤",
    "😴",
  ],
  [
    "👋",
    "🤚",
    "🖐",
    "✋",
    "🖖",
    "👌",
    "🤌",
    "🤏",
    "✌",
    "🤞",
    "🤟",
    "🤘",
    "🤙",
    "👈",
    "👉",
    "👆",
    "🖕",
    "👇",
    "☝",
    "👍",
    "👎",
    "✊",
    "👊",
    "🤛",
    "🤜",
    "👏",
    "🙌",
    "🫶",
    "👐",
    "🤲",
    "🙏",
    "✍",
    "💅",
    "🤳",
    "💪",
    "🦾",
  ],
  [
    "❤",
    "🧡",
    "💛",
    "💚",
    "💙",
    "💜",
    "🖤",
    "🤍",
    "🤎",
    "💔",
    "❤‍🔥",
    "❤‍🩹",
    "❣",
    "💕",
    "💞",
    "💓",
    "💗",
    "💖",
    "💘",
    "💝",
    "💟",
    "♥",
    "🫀",
  ],
  [
    "🌸",
    "🌺",
    "🌻",
    "🌹",
    "🌷",
    "🌼",
    "💐",
    "🍀",
    "🌿",
    "☘",
    "🍃",
    "🌱",
    "🌲",
    "🌳",
    "🌴",
    "🌵",
    "🎋",
    "🎍",
    "🍄",
    "🌾",
    "🌊",
    "🌈",
    "⭐",
    "🌙",
    "☀",
    "⛅",
    "🌤",
    "🌦",
  ],
  [
    "🍕",
    "🍔",
    "🍟",
    "🌭",
    "🥪",
    "🥙",
    "🧆",
    "🌮",
    "🌯",
    "🫔",
    "🍳",
    "🥘",
    "🫕",
    "🍲",
    "🥗",
    "🍿",
    "🍱",
    "🍘",
    "🍙",
    "🍚",
    "🍛",
    "🍜",
    "🍝",
    "🍞",
    "🥐",
    "🥖",
    "🫓",
    "🥨",
  ],
];

export const EMOJI_CATEGORIES_KEYS = [
  "smileys",
  "gestures",
  "hearts",
  "nature",
  "food",
] as const;

export const QUICK_REACTIONS = ["👍", "❤️", "😂", "😮", "😢", "🔥"];

export const AI_SUGGESTIONS = [
  "Sure, that sounds great! Let know when you are free.",
  "Thanks for sharing! I will review it and get back to you soon.",
  "Interesting point! Could you elaborate a bit more on that?",
  "Absolutely, I agree with you on this one.",
  "I will take care of it right away!",
  "That makes sense. Let me think about it and respond shortly.",
];

/** Подписи ролей участника группы. */
export const CHAT_ROLE_LABELS = {
  owner: "Владелец",
  admin: "Администратор",
  member: "Участник",
} as const;

/** Права чата из effective permissions auth/me. Скрывают UI, доступ решает бэкенд. */
export const CHAT_PERMISSIONS = {
  VIEW: "chat.view",
  CREATE: "chat.create",
  SEND: "chat.send",
  GROUP_MANAGE: "chat.group.manage",
  DELETE: "chat.delete",
} as const;

export const STORY_IMAGES = [
  "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=300&q=80",
  "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=300&q=80",
  "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=300&q=80",
  "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=300&q=80",
  "https://images.unsplash.com/photo-1472214103451-9374bd1c798e?w=300&q=80",
  "https://images.unsplash.com/photo-1433086966358-54859d0ed716?w=300&q=80",
  "https://images.unsplash.com/photo-1426604966848-d7adac402bff?w=300&q=80",
];
