export const MODULE_TRANSLATIONS: Record<string, string> = {
  profile: "Личный кабинет",
  users: "Персонал",
  roles: "Роли",
  permissions: "Права доступа",
  organizations: "Организации",
  departments: "Отделы",
  tasks: "Чат / Задачи",
  events: "События",
  correspondence: "Корреспонденция",
  internal_correspondence: "Внутренняя корреспонденция",
  signatures: "Подписи",
  analytics: "Аналитика",
  approvals: "Согласования",
  system: "Системные функции",
};

export const ACTION_TRANSLATIONS: Record<string, string> = {
  view: "Просмотр",
  create: "Создание",
  update: "Редактирование",
  delete: "Удаление",
  manage_ui: "Управление UI",
  register: "Регистрация",
  assign: "Назначение",
  "assignment.update_status": "Изменение статуса",
  view_all: "Просмотр всех",
  update_all: "Обновление всех",
  "assignment.update_any": "Обновление любого",
  edit_own: "Собственное",
  "folder.view": "Просмотр папок",
  "folder.manage": "Управление папок",
  sign: "Подписание",
  reject: "Отклонение",
  export: "Экспорт",
  "logs.view": "Просмотр логов",
};
