export const AppRoutes = {
  LOGIN: "/auth/login",
  PROFILE: "/profile",
  PROFILE_TASKS: "/profile/tasks",
  PROFILE_CALENDAR: "/profile/calendar",
  PROFILE_ANALYTICS: "/profile/analytics",
  MODULES: "/modules",
  CORRESPONDENCE: "/modules/correspondence",
  CORRESPONDENCE_INCOMING: "/modules/correspondence/incoming",
  CORRESPONDENCE_INCOMING_CREATE: "/modules/correspondence/incoming/create",
  CORRESPONDENCE_OUTGOING: "/modules/correspondence/outgoing",
  CORRESPONDENCE_OUTGOING_CREATE: "/modules/correspondence/outgoing/create",
  CORRESPONDENCE_ARCHIVE: "/modules/correspondence/archive",
  CORRESPONDENCE_PINNED: "/modules/correspondence/pinned",
  CORRESPONDENCE_FOLDERS: "/modules/correspondence/folders",
  CORRESPONDENCE_TRASHED: "/modules/correspondence/trashed",
  CORRESPONDENCE_INCOMING_SHOW: "/modules/correspondence/incoming/:id",
} as const;
