export const AppRoutes = {
  LOGIN: "/auth/login",
  PROFILE: "/profile",
  PROFILE_TASKS: "/profile/tasks",
  PROFILE_CALENDAR: "/profile/calendar",
  PROFILE_ANALYTICS: "/profile/analytics",
  MODULES: "/modules",
  CORRESPONDENCE: "/modules/correspondence",
  CORRESPONDENCE_INCOMING: "/modules/correspondence/incoming",
  CORRESPONDENCE_OUTGOING: "/modules/correspondence/outgoing",
  CORRESPONDENCE_ARCHIVE: "/modules/correspondence/archive",
  CORRESPONDENCE_PINNED: "/modules/correspondence/pinned",
  CORRESPONDENCE_FOLDERS: "/modules/correspondence/folders",
  CORRESPONDENCE_TRASH: "/modules/correspondence/trash",
} as const;