import { ApiRoutes } from "@shared/api";

export const CORRESPONDENCE_INVALIDATE_KEYS = [
  ApiRoutes.GET_CORRESPONDENCES,
  ApiRoutes.GET_COUNTERS_CORRESPONDENCE,
  ApiRoutes.GET_INTERNAL_CORRESPONDENCES,
  ApiRoutes.GET_INTERNAL_INCOMING,
  ApiRoutes.GET_INTERNAL_OUTGOING,
  ApiRoutes.GET_INTERNAL_DRAFTS,
  ApiRoutes.GET_INTERNAL_TRASH,
  ApiRoutes.GET_INTERNAL_COUNTERS,
  ApiRoutes.GET_INTERNAL_TO_SIGN,
  ApiRoutes.GET_INTERNAL_TO_APPROVE,
  ApiRoutes.GET_INTERNAL_PROCESSED,
];
