import type { Colleague, Task } from "./types";

/**
 * Временные mock-данные модуля «Задачи».
 *
 * ТОЧКА ЗАМЕНЫ НА API: это единственный источник фейковых данных. Когда бэкенд
 * будет готов, заменяем импорт этих констант на реальные запросы в useTasks.ts
 * (коллеги → GET /api/v1/tasks/assignees, задачи → GET /api/v1/tasks), не меняя
 * UI-компоненты. Недостающие для дизайна поля перечислены в useTasks.ts.
 */

export const MOCK_COLLEAGUES: Colleague[] = [
  { id: "1", name: "Алишер Махмудов", role: "Fullstack Developer", initials: "АМ", color: "bg-blue-500" },
  { id: "2", name: "Зарина Ибрагимова", role: "UI/UX Designer", initials: "ЗИ", color: "bg-emerald-500" },
  { id: "3", name: "Рустам Назаров", role: "Team Lead", initials: "РН", color: "bg-purple-500" },
  { id: "4", name: "Нилуфар Рахимова", role: "QA Engineer", initials: "НР", color: "bg-rose-500" },
  { id: "5", name: "Даврон Хасанов", role: "Backend Developer", initials: "ДХ", color: "bg-amber-500" },
  { id: "6", name: "Мадина Юсупова", role: "Product Manager", initials: "МЮ", color: "bg-indigo-500" },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: "TSK-1024",
    title: "Разработка API для модуля авторизации",
    description:
      "Необходимо реализовать эндпоинты для регистрации, логина и восстановления пароля с использованием JWT.",
    status: "in_progress",
    priority: "high",
    assignee: MOCK_COLLEAGUES[0],
    dueDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 2).toISOString(),
    createdAt: new Date().toISOString(),
    tags: ["Backend", "Security", "Auth"],
    progress: 65,
    attachments: [
      { id: "a1", name: "api_spec.pdf", type: "PDF", size: "1.2 MB" },
      { id: "a2", name: "diagram.png", type: "PNG", size: "450 KB" },
    ],
  },
  {
    id: "TSK-1025",
    title: "Миграция базы данных PostgreSQL",
    description:
      "Перенос таблиц пользователей и транзакций на новую схему для повышения производительности.",
    status: "new",
    priority: "critical",
    assignee: MOCK_COLLEAGUES[4],
    dueDate: new Date(Date.now() + 1000 * 60 * 60 * 5).toISOString(),
    createdAt: new Date().toISOString(),
    tags: ["DB", "DevOps"],
    progress: 0,
    attachments: [],
  },
  {
    id: "TSK-1026",
    title: "Настройка CI/CD пайплайна",
    description:
      "Автоматизация сборки и деплоя фронтенд-приложения в тестовое окружение.",
    status: "review",
    priority: "medium",
    assignee: MOCK_COLLEAGUES[2],
    dueDate: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    createdAt: new Date().toISOString(),
    tags: ["CI/CD", "GitHub Actions"],
    progress: 90,
    attachments: [],
  },
  {
    id: "TSK-1027",
    title: "Ревью дизайна личного кабинета",
    description:
      "Проверка соответствия макетов текущему брендбуку и UI-киту компании.",
    status: "completed",
    priority: "low",
    assignee: MOCK_COLLEAGUES[1],
    dueDate: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    createdAt: new Date().toISOString(),
    tags: ["Design", "Review"],
    progress: 100,
    attachments: [],
  },
  {
    id: "TSK-1028",
    title: "Нагрузочное тестирование платежной системы",
    description: "Имитация 10 000 RPS для выявления узких мест в обработке очередей.",
    status: "in_progress",
    priority: "critical",
    assignee: MOCK_COLLEAGUES[4],
    dueDate: new Date(Date.now() + 1000 * 60 * 60 * 36).toISOString(),
    createdAt: new Date().toISOString(),
    tags: ["Testing", "Backend"],
    progress: 30,
    attachments: [],
  },
  {
    id: "TSK-1029",
    title: "Оптимизация бандла фронтенда",
    description:
      "Уменьшение размера JS-файлов через code-splitting и удаление неиспользуемых библиотек.",
    status: "new",
    priority: "medium",
    assignee: MOCK_COLLEAGUES[0],
    dueDate: new Date(Date.now() + 1000 * 60 * 60 * 72).toISOString(),
    createdAt: new Date().toISOString(),
    tags: ["Frontend", "Performance"],
    progress: 10,
    attachments: [],
  },
  {
    id: "TSK-1030",
    title: "Подготовка отчетности за Q1",
    description: "Сбор статистики по выполненным задачам и KPI команды.",
    status: "completed",
    priority: "high",
    assignee: MOCK_COLLEAGUES[5],
    dueDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    createdAt: new Date().toISOString(),
    tags: ["Management"],
    progress: 100,
    attachments: [],
  },
  {
    id: "TSK-1031",
    title: "Обновление документации API",
    description:
      "Актуализация Swagger описания после внедрения новых методов фильтрации.",
    status: "in_progress",
    priority: "low",
    assignee: MOCK_COLLEAGUES[0],
    dueDate: new Date(Date.now() + 1000 * 60 * 60 * 120).toISOString(),
    createdAt: new Date().toISOString(),
    tags: ["Documentation"],
    progress: 45,
    attachments: [],
  },
  {
    id: "TSK-1032",
    title: "Рефакторинг модуля уведомлений",
    description: "Переход на сокеты для мгновенного получения пуш-уведомлений.",
    status: "review",
    priority: "medium",
    assignee: MOCK_COLLEAGUES[4],
    dueDate: new Date(Date.now() + 1000 * 60 * 60 * 10).toISOString(),
    createdAt: new Date().toISOString(),
    tags: ["Refactoring", "Realtime"],
    progress: 85,
    attachments: [],
  },
  {
    id: "TSK-1033",
    title: "Интеграция с сервисом SMS-рассылок",
    description: "Подключение внешнего провайдера для верификации номеров телефонов.",
    status: "new",
    priority: "high",
    assignee: MOCK_COLLEAGUES[0],
    dueDate: new Date(Date.now() + 1000 * 60 * 60 * 48).toISOString(),
    createdAt: new Date().toISOString(),
    tags: ["Integration"],
    progress: 5,
    attachments: [],
  },
  {
    id: "TSK-1034",
    title: "Фикс багов мобильной версии",
    description: "Исправление верстки шапки и меню на экранах менее 375px.",
    status: "overdue",
    priority: "high",
    assignee: MOCK_COLLEAGUES[1],
    dueDate: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    createdAt: new Date().toISOString(),
    tags: ["Mobile", "Bug"],
    progress: 90,
    attachments: [],
  },
  {
    id: "TSK-1035",
    title: "Внедрение микросервиса логирования",
    description: "Сбор логов со всех сервисов в единое хранилище ELK.",
    status: "in_progress",
    priority: "medium",
    assignee: MOCK_COLLEAGUES[4],
    dueDate: new Date(Date.now() + 1000 * 60 * 60 * 200).toISOString(),
    createdAt: new Date().toISOString(),
    tags: ["Infrastructure"],
    progress: 25,
    attachments: [],
  },
  {
    id: "TSK-1036",
    title: "Создание лендинга для рекрутинга",
    description: 'Разработка страницы "Карьера" с формами отклика.',
    status: "new",
    priority: "low",
    assignee: MOCK_COLLEAGUES[1],
    dueDate: new Date(Date.now() + 1000 * 60 * 60 * 150).toISOString(),
    createdAt: new Date().toISOString(),
    tags: ["Marketing", "Frontend"],
    progress: 0,
    attachments: [],
  },
  {
    id: "TSK-1037",
    title: "Аудит безопасности сервера",
    description: "Проверка открытых портов и прав доступа к файловой системе.",
    status: "review",
    priority: "critical",
    assignee: MOCK_COLLEAGUES[3],
    dueDate: new Date(Date.now() + 1000 * 60 * 60 * 4).toISOString(),
    createdAt: new Date().toISOString(),
    tags: ["Security"],
    progress: 95,
    attachments: [],
  },
  {
    id: "TSK-1038",
    title: "Ежедневный бэкап БД",
    description: "Настройка скрипта автоматического резервного копирования.",
    status: "completed",
    priority: "high",
    assignee: MOCK_COLLEAGUES[2],
    dueDate: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    createdAt: new Date().toISOString(),
    tags: ["DevOps", "Data"],
    progress: 100,
    attachments: [],
  },
];
